### ISSUE TITLE
AssertionError: Invalid pin: ACBUS5.

### ISSUE THREAD

**Issue by naamah75** [Wei1234c/Bridges#1]
I'm pretty sure that insn't an issue, but in the documentation I've not found any solution.
So, my board is an FT323H with ACBUS0 to ACBUS9  and ADBUS0 to 7, but I can't figure out how to select te ACBUS.
When I try to address it, whit some like that
`p1 = machine.Pin('ACBUS5', Pin.IN, Pin.PULL_UP)`
I got this error
```
  File "/home/igor/PycharmProjects/FT232H/venv/bridges/ftdi/controllers/spi.py", line 173, in Pin
    assert id in self.addressable_pins.keys() or \
AssertionError: Invalid pin: ACBUS5.
 Addressable pins: {'ADBUS0': 0, 'ADBUS1': 1, 'ADBUS2': 2, 'ADBUS3': 3, 'ADBUS4': 4, 'ADBUS5': 5, 'ADBUS6': 6, 'ADBUS7': 7}
```
Anyone can help-me?

**Comment by Wei1234c** [comment]
Sorry for late response. 

My package depends on [PyFtdi](https://github.com/eblot/pyftdi), which offers three ways to open up GPIO ports:

**1. pyftdi.gpio:**
- **GpioAsyncController** : GPIO accessible pins are limited to the 8 lower pins of each GPIO port.
- **GpioSyncController**: GPIO accessible pins are limited to the 8 lower pins of each GPIO port.
- **GpioMpsseController**: All GPIO pins are reachable, but MPSSE mode is **slower** than other modes.

`bridges.ftdi.controllers.gpio.GpioController` is a subclass of `pyftdi.gpio.GpioAsyncController`,  which can access only the 8 lower pins of each GPIO port. 

So, if you go with following code:
```
from bridges.ftdi.controllers.gpio import GpioController
from bridges.interfaces.micropython.machine import Pin

machine = GpioController()
print(machine.addressable_pins)

p0 = machine.Pin('ACBUS5', mode = Pin.OUT)
```
which shows addressable pins as `
{'ADBUS0': 0, 'ADBUS1': 1, 'ADBUS2': 2, 'ADBUS3': 3, 'ADBUS4': 4, 'ADBUS5': 5, 'ADBUS6': 6, 'ADBUS7': 7}` and `ACBUS5` un-accessable.

  
**2. pyftdi.i2c** (I didn't implement this)**:**
- **I2cController**: the lowest 3 bits are reserved for I2C, other 13 bits are available for GPIOs.

  
  

**3. pyftdi.spi:**
- **SpiController**: the lowest 4 bits are reserved for SPI, other 12 bits are available for GPIOs.

So, ACBUS5  is accessable with following code:

```
from bridges.ftdi.controllers.spi import SpiController
from bridges.interfaces.micropython.machine import Pin

ctrl = SpiController()
machine = ctrl.get_gpio()

print(machine.addressable_pins)
p0 = machine.Pin('ACBUS5', mode = Pin.OUT)

print(p0.value())

p0.value(0)
print(p0.value())

p0.value(1)
print(p0.value())
```

which shows addressable pins as `
{'ADBUS4': 4, 'ADBUS5': 5, 'ADBUS6': 6, 'ADBUS7': 7, 'ACBUS0': 8, 'ACBUS1': 9, 'ACBUS2': 10, 'ACBUS3': 11, 'ACBUS4': 12, 'ACBUS5': 13, 'ACBUS6': 14, 'ACBUS7': 15}` (note that the lowest 4 bits are left out).


---
I implement `bridges.ftdi.controllers.i2c.I2cGpioPort` today (2022/1/14), so following code:
```
from bridges.ftdi.controllers.i2c import I2cController
from bridges.interfaces.micropython.machine import Pin

ctrl = I2cController()
machine = ctrl.get_gpio()

print(machine.addressable_pins)
p0 = machine.Pin('ACBUS5', mode = Pin.OUT)
```
will show addressable pins as `
{'ADBUS3': 3, 'ADBUS4': 4, 'ADBUS5': 5, 'ADBUS6': 6, 'ADBUS7': 7, 'ACBUS0': 8, 'ACBUS1': 9, 'ACBUS2': 10, 'ACBUS3': 11, 'ACBUS4': 12, 'ACBUS5': 13, 'ACBUS6': 14, 'ACBUS7': 15}` (note that the lowest 3 bits are left out).



---
I implement `bridges.ftdi.controllers.gpio.GpioMpsseController` today (2022/1/17), so following code:
```
from bridges.ftdi.controllers.gpio import GpioMpsseController as GpioController
from bridges.interfaces.micropython.machine import Pin

machine = GpioController()
print(machine.addressable_pins)

pin_1 = machine.Pin('ADBUS5', mode = Pin.OUT)
pin_2 = machine.Pin('ACBUS5', mode = Pin.OUT)
```
will show addressable pins as `{'ADBUS0': 0, 'ADBUS1': 1, 'ADBUS2': 2, 'ADBUS3': 3, 'ADBUS4': 4, 'ADBUS5': 5, 'ADBUS6': 6, 'ADBUS7': 7, 'ACBUS0': 8, 'ACBUS1': 9, 'ACBUS2': 10, 'ACBUS3': 11, 'ACBUS4': 12, 'ACBUS5': 13, 'ACBUS6': 14, 'ACBUS7': 15}` and all 16 bits are accessable.
